// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7dHGv8DLy32lgwEQtJCyRjwsF-2-U2H4',
    appId: '1:685279846619:android:6e4966d86b6fb9730b2cfe',
    messagingSenderId: '685279846619',
    projectId: 'lab6csi464',
    storageBucket: 'lab6csi464.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbaDCNPeGJcaXM1-pFAwX1aQQcc89txeE',
    appId: '1:685279846619:ios:0c964bbb610855a30b2cfe',
    messagingSenderId: '685279846619',
    projectId: 'lab6csi464',
    storageBucket: 'lab6csi464.appspot.com',
    iosClientId: '685279846619-p2v25hmsokjpgo8cmttoanov4h1uknq2.apps.googleusercontent.com',
    iosBundleId: 'com',
  );
}
